export const reqConstants = {
  REQS_REQUEST: "REQS_REQUEST",
  REQS_SUCCESS: "REQS_SUCCESS",
  REQS_FAILURE: "REQS_FAILURE",

  REQS_GETALL_REQUEST: "REQS_GETALL_REQUEST",
  REQS_GETALL_SUCCESS: "REQS_GETALL_SUCCESS",
  REQS_GETALL_FAILURE: "REQS_GETALL_FAILURE",

  REQ_COMMIT_REQUEST: "REQ_COMMIT_REQUEST",
  REQ_COMMIT_SUCCESS: "REQ_COMMIT_SUCCESS",
  REQ_COMMIT_FAILURE: "REQ_COMMIT_FAILURE",
};
