export const reqConstants = {
    REQS_REQUEST: 'REQS_REQUEST',
    REQS_SUCCESS: 'REQS_SUCCESS',
    REQS_FAILURE: 'REQS_FAILURE',

    REQS_GETALL_REQUEST: 'REQS_GETALL_REQUEST',
    REQS_GETALL_SUCCESS: 'REQS_GETALL_SUCCESS',
    REQS_GETALL_FAILURE: 'REQS_GETALL_FAILURE',
};
